[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "Gallery"
  pageRef = "/gallery"
  weight = 30

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 40
